version: "3.8"
services:
  backend:
    build: .
    ports:
      - "8000:8000"

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    command: ["coverage", "run", "-m", "pytest", "tests"]