name: CI - Backend

on:
  push:
    branches:
      - main
      - develop
      - feat/**
      - fix/**
  pull_request:

jobs:
  test:
    name: Run tests and check coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with coverage
        working-directory: backend
        run: |
          coverage run -m pytest tests
          coverage report
          coverage xml

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: backend/coverage.xml
